/*
Copyright 2023 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	kahumgrv1beta1 "github.com/soda-cdm/kahu-manager/apis/kahumgr/v1beta1"
	versioned "github.com/soda-cdm/kahu-manager/client/clientset/versioned"
	internalinterfaces "github.com/soda-cdm/kahu-manager/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/soda-cdm/kahu-manager/client/listers/kahumgr/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SchedulePolicyInformer provides access to a shared informer and lister for
// SchedulePolicies.
type SchedulePolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.SchedulePolicyLister
}

type schedulePolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSchedulePolicyInformer constructs a new informer for SchedulePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSchedulePolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSchedulePolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSchedulePolicyInformer constructs a new informer for SchedulePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSchedulePolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KahumgrV1beta1().SchedulePolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KahumgrV1beta1().SchedulePolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&kahumgrv1beta1.SchedulePolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *schedulePolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSchedulePolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *schedulePolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kahumgrv1beta1.SchedulePolicy{}, f.defaultInformer)
}

func (f *schedulePolicyInformer) Lister() v1beta1.SchedulePolicyLister {
	return v1beta1.NewSchedulePolicyLister(f.Informer().GetIndexer())
}
